// Map TxLINE team names → ISO 3166-1 alpha-2 codes (lowercase) for flag-icons.
// Emoji flags don't render on Windows, so we use real SVG flags via the `fi fi-xx` classes.
// England/Scotland/Wales use flag-icons' subdivision codes (gb-eng, gb-sct, gb-wls).
const CODES: Record<string, string> = {
  Albania: "al",
  Algeria: "dz",
  Argentina: "ar",
  Australia: "au",
  Austria: "at",
  Belgium: "be",
  Bolivia: "bo",
  "Bosnia & Herzegovina": "ba",
  "Bosnia and Herzegovina": "ba",
  Brazil: "br",
  Bulgaria: "bg",
  Cameroon: "cm",
  Canada: "ca",
  "Cape Verde": "cv",
  "Cabo Verde": "cv",
  Chile: "cl",
  China: "cn",
  "China PR": "cn",
  Colombia: "co",
  "Congo DR": "cd",
  "DR Congo": "cd",
  "Costa Rica": "cr",
  Croatia: "hr",
  Czechia: "cz",
  "Czech Republic": "cz",
  Denmark: "dk",
  Ecuador: "ec",
  Egypt: "eg",
  "El Salvador": "sv",
  England: "gb-eng",
  Estonia: "ee",
  Finland: "fi",
  France: "fr",
  Germany: "de",
  Ghana: "gh",
  Greece: "gr",
  Guinea: "gn",
  Haiti: "ht",
  Honduras: "hn",
  Hungary: "hu",
  Iceland: "is",
  India: "in",
  Indonesia: "id",
  Iran: "ir",
  "IR Iran": "ir",
  Iraq: "iq",
  Ireland: "ie",
  "Republic of Ireland": "ie",
  Israel: "il",
  Italy: "it",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  "Cote d'Ivoire": "ci",
  Jamaica: "jm",
  Japan: "jp",
  Jordan: "jo",
  Kazakhstan: "kz",
  Kenya: "ke",
  Kosovo: "xk",
  Kuwait: "kw",
  Mexico: "mx",
  Morocco: "ma",
  Netherlands: "nl",
  "New Zealand": "nz",
  Nigeria: "ng",
  "North Macedonia": "mk",
  Norway: "no",
  Panama: "pa",
  Paraguay: "py",
  Peru: "pe",
  Poland: "pl",
  Portugal: "pt",
  Qatar: "qa",
  Romania: "ro",
  "Saudi Arabia": "sa",
  Scotland: "gb-sct",
  Senegal: "sn",
  Serbia: "rs",
  Slovakia: "sk",
  Slovenia: "si",
  "South Africa": "za",
  "South Korea": "kr",
  "Korea Republic": "kr",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Tunisia: "tn",
  Turkey: "tr",
  "Türkiye": "tr",
  Ukraine: "ua",
  "United Arab Emirates": "ae",
  UAE: "ae",
  USA: "us",
  "United States": "us",
  Uruguay: "uy",
  Uzbekistan: "uz",
  Venezuela: "ve",
  Vietnam: "vn",
  Wales: "gb-wls",
};

/** ISO code for a team name, or null if unknown. */
export function flagCode(team: string): string | null {
  return CODES[team] ?? null;
}
